server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ProcessAudit AI Application Logs
  - job_name: processaudit-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: processaudit-app
          __path__: /var/log/processaudit/*.log

  # Docker Container Logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # System Logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # ProcessAudit AI Specific Logs
  - job_name: processaudit-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: processaudit-api
          __path__: /var/log/processaudit/api/*.log

    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            correlation_id: correlation_id
            organization_id: organization_id
            user_id: user_id
      - labels:
          level:
          correlation_id:
          organization_id:
      - timestamp:
          format: RFC3339
          source: timestamp